### ISSUE TITLE
Self signed certificate

### ISSUE THREAD

**Issue by hillbicks** [mardy/ttrss#1]
Hey there,

I just got my BQ today and ttrss was the first app I installed. Unfortunately I couldn't get it working, presumably because the certificate I'm using is self signed with the https URL. Nothing happens after clicking the sign in button, so I guess it's related to the cert. I couldn't find a way to import the cert through ubuntu itself.

Do you know any workaround?

Thanks for working on this!

**Comment by mardy** [comment]
Hi! If the URL of the server address starts with "https", a checkox "Ignore SSL errors" should appear below, and that should instruct TTRSS to ignore all SSL errors. Did you toggle this checkbox?

**Comment by hillbicks** [comment]
Sorry for the late response, I investigated a bit further and it seems that there isn't any outgoing connection since I don't even see a request in my server logs from the ubuntu phone when using the app. I do see entries in the log when I open the same url in the browser though.

I also tried another url, which didn't do anything either

https://www.softaculous.com/demos/Tiny_Tiny_RSS

Upon pressing the Login button, there is a short vibration but no other feedback and nothing happens. Is there some special format regarding the URL?

Oh, btw. I see the checkbox when I enter https, but there is no description next to it, so I assumed it would be to remember the password. I guess that's also not how it's supposed to be, right?

**Comment by mardy** [comment]
Oh, your right, that option didn't work at all. I just uploaded a new version of the app which should fix that. The demo site you linked cannot work, because it's configured with the API disabled.

The format for the URL is the usual one: just make sure that it starts with "https://".

Please let me know if this new version (0.5.1-0) fixes the problem.

**Comment by hillbicks** [comment]
Fantastic! Thanks very much, it works now! I see the description next to the checkbox and I can login, so I'm closing this issue.
