### ISSUE TITLE
Margin on article list

### ISSUE THREAD

**Issue by onlygecko** [mardy/ttrss#3]
It would be great to have a left-margin and right-margin on the article list. This would it make easier to scan the available articles.

**Comment by mardy** [comment]
Hi! I don't understand what exactly you mean, could you please take a screenshot and mark there where margins should be added?
(the article list already has some margins, and I don't understand how increasing them would make scanning easier)

**Comment by onlygecko** [comment]
I think the margin shoud be, where the the blue lines are. This margin mustn't be very wide. The message view in Dekka is probably a good example.

![screenshot20150626_165147150](https://cloud.githubusercontent.com/assets/3233376/8380325/6b964554-1c25-11e5-82a6-ef2e2be702f8.png)
![screenshot20150626_165154976](https://cloud.githubusercontent.com/assets/3233376/8380326/6b9a36b4-1c25-11e5-8e8c-885a258c7177.png)

**Comment by mardy** [comment]
I see, thanks. I agree, I'll fix it when time allows.

**Comment by mardy** [comment]
This is now fixed in master. There are a few other changes that I want to do before releasing it, but anyway expect a release soon :-)
