### ISSUE TITLE
"mark as read" action

### ISSUE THREAD

**Issue by onlygecko** [mardy/ttrss#5]
I hope I'm not annoying you mardy... ;-)

I would love to mark an article or an feed as read, so I don't have to view every article to have the same effect. I often scan articles by the title and first lines an mark the ones I won't read as read.

**Comment by mardy** [comment]
You are not annoying, on the contrary you are giving me motivation to continue working on this. :-)

I will add the feature of marking the current feed as read.

**Comment by onlygecko** [comment]
I would love to help pushing this project. Unfortunately I'm neither familiar with c++ nor with QML. So anytime soon I could just test new features, contribute to the documentation, translate and report a lot of feature wishes. ;-)

**Comment by mardy** [comment]
Fixed in master. Will be released soon.
